package com.quran.mobile.persiantafsir.data

import app.cash.sqldelight.driver.jdbc.sqlite.JdbcSqliteDriver
import com.google.common.truth.Truth.assertThat
import com.quran.labs.androidquran.pages.data.madani.MadaniDataSource
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.io.File

/**
 * Verifies the bundled asset generated by tools/persian-tafsir/convert.mjs against the app's
 * own Quran metadata, using the same SQLDelight queries the app runs.
 */
class PersianTafsirDatabaseTest {
  private lateinit var driver: JdbcSqliteDriver
  private lateinit var queries: PersianTafsirQueries

  @Before
  fun setup() {
    val asset = File("../../app/src/main/assets/persian_tafsir.db")
    assertThat(asset.exists()).isTrue()
    // work on a copy so the test can never modify the bundled asset
    val copy = File.createTempFile("persian_tafsir", ".db").apply { deleteOnExit() }
    asset.copyTo(copy, overwrite = true)
    driver = JdbcSqliteDriver("jdbc:sqlite:${copy.absolutePath}")
    queries = PersianTafsirDatabase(driver).persianTafsirQueries
  }

  @After
  fun tearDown() {
    driver.close()
  }

  private fun range(startSura: Int, startAyah: Int, endSura: Int, endAyah: Int) =
    queries.tafsirForRange(startSura * 1000L + startAyah, endSura * 1000L + endAyah)
      .executeAsList()

  @Test
  fun everySurahHasTheExpectedNumberOfAyahs() {
    val expected = MadaniDataSource().numberOfAyahsForSuraArray
    val all = range(1, 1, 114, 6)
    assertThat(all).hasSize(6236)

    val counts = all.groupingBy { it.sura.toInt() }.eachCount()
    expected.forEachIndexed { index, count ->
      assertThat(counts[index + 1]).isEqualTo(count)
    }
    assertThat(all.all { it.text.isNotBlank() }).isTrue()
  }

  @Test
  fun ayahsAreNumberedSequentially() {
    val all = range(1, 1, 114, 6)
    all.groupBy { it.sura }.values.forEach { ayat ->
      assertThat(ayat.map { it.ayah.toInt() }).isEqualTo((1..ayat.size).toList())
    }
  }

  @Test
  fun knownAyahsMatch() {
    assertThat(range(2, 1, 2, 1).single().text).isEqualTo("الف، لام، میم.")
    assertThat(range(36, 1, 36, 1).single().text).isEqualTo("یا، سین.")
    assertThat(range(1, 1, 1, 1).single().text).startsWith("به نام اللهِ")
    // Ghafir switches Word numbering lists at ayah 76; the text must not drift
    assertThat(range(40, 76, 40, 76).single().text).contains("جهنّم")
  }

  @Test
  fun rangeSpansSurahs() {
    val ayat = range(1, 7, 2, 2)
    assertThat(ayat.map { it.sura to it.ayah }).containsExactly(1L to 7L, 2L to 1L, 2L to 2L)
      .inOrder()
    assertThat(ayat.first().name).isEqualTo("فاتحه")
    assertThat(ayat.last().name).isEqualTo("بقره")
  }

  @Test
  fun bismillahIsMissingOnlyForFatihaAndTawbah() {
    val all = range(1, 1, 114, 6).filter { it.ayah == 1L }
    assertThat(all).hasSize(114)
    val withoutBismillah = all.filter { it.bismillah == null }.map { it.sura.toInt() }
    assertThat(withoutBismillah).containsExactly(1, 9)
  }
}
