package com.quran.labs.androidquran.common.ui.core
import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF1F4E56)
val lightOnPrimary = Color(0xFFF7F0E1)
val lightPrimaryContainer = Color(0xFFD5E6E8)
val lightOnPrimaryContainer = Color(0xFF143A40)
val lightSecondary = Color(0xFF3C6B6D)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFDCEAEA)
val lightOnSecondaryContainer = Color(0xFF143A40)
val lightTertiary = Color(0xFF7E5A1C)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFF1E2C0)
val lightOnTertiaryContainer = Color(0xFF3A2A08)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFF7F0E1)
val lightOnBackground = Color(0xFF1C1A16)
val lightSurface = Color(0xFFFCF8EF)
val lightOnSurface = Color(0xFF1C1A16)
val lightSurfaceVariant = Color(0xFFEDE4D0)
val lightOnSurfaceVariant = Color(0xFF5A5347)
val lightOutline = Color(0xFF8A8170)
val lightInverseOnSurface = Color(0xFFF7F0E1)
val lightInverseSurface = Color(0xFF2E2B25)
val lightInversePrimary = Color(0xFF8CCADB)
val lightShadow = Color(0xFF000000)
val lightSurfaceTint = Color(0xFF1F4E56)
val lightSurfaceColorHighest = Color(0xFFF7F0E1)

val darkPrimary = Color(0xFF8CCADB)
val darkOnPrimary = Color(0xFF0E1518)
val darkPrimaryContainer = Color(0xFF1F4E56)
val darkOnPrimaryContainer = Color(0xFFD5E6E8)
val darkSecondary = Color(0xFFA9C9CC)
val darkOnSecondary = Color(0xFF143A40)
val darkSecondaryContainer = Color(0xFF2A3A40)
val darkOnSecondaryContainer = Color(0xFFDCEAEA)
val darkTertiary = Color(0xFFE3C58A)
val darkOnTertiary = Color(0xFF3A2A08)
val darkTertiaryContainer = Color(0xFF5C4416)
val darkOnTertiaryContainer = Color(0xFFF1E2C0)
val darkError = Color(0xFFFFB4AB)
val darkErrorContainer = Color(0xFF93000A)
val darkOnError = Color(0xFF690005)
val darkOnErrorContainer = Color(0xFFFFDAD6)
val darkBackground = Color(0xFF0E1518)
val darkOnBackground = Color(0xFFE8E0CC)
val darkSurface = Color(0xFF1A252A)
val darkOnSurface = Color(0xFFE8E0CC)
val darkSurfaceVariant = Color(0xFF2A3A40)
val darkOnSurfaceVariant = Color(0xFFA9A08C)
val darkOutline = Color(0xFF7D8A8E)
val darkInverseOnSurface = Color(0xFF0E1518)
val darkInverseSurface = Color(0xFFE8E0CC)
val darkInversePrimary = Color(0xFF1F4E56)
val darkShadow = Color(0xFF000000)
val darkSurfaceTint = Color(0xFF8CCADB)
val darkSurfaceColorHighest = Color(0xFF0E1518)

// Tasnim identity: dark teal #1F4E56, cream #F7F0E1, gold #C8A45E; night #0E1518.
